services:
  nginx:
    volumes:
      - ./deploy/nginx/zeronight.docker.https.generated.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - ./deploy/certbot/www:/var/www/certbot:ro
      - ./deploy/certbot/conf:/etc/letsencrypt:ro
